version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: abdelrahmanraheel/flask-mysql-app
    container_name: flask-mysql-app
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=Mydata
    depends_on:
      - db
    networks:
      - mynetwork
    restart: always

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=Mydata
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
